
name: Build Release

on:
  push:
    tags: release-[1-9]+.[0-9]+.[0-9]+
    branches: master

jobs:
  test:
    runs-on: ubuntu-18.04
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: false     
      matrix:   
        php-version: ['7.4']
        experimental: [false]

    steps:
      - uses: actions/checkout@v2

      - name: Find the version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Show the discovered version
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}

      - name: Set up PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Setup Packages
        run: |
          cd $GITHUB_WORKSPACE
          sudo apt update

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        uses: php-actions/composer@v5
        with:
          dev: yes
          args: --prefer-dist --no-interaction
          php_version: 7.4
          php_extensions: xml 
          version: 2

      - name: Create Database
        run: |
          sudo systemctl start mysql.service
          sudo mysql -proot  -e 'drop database if exists phplistdb'
          sudo mysqladmin -proot create phplistdb
          sudo mysql -proot -e 'grant all on phplistdb.* to phplist@"%" identified by "phplist"'

      - name: Start Test Server
        run: |
          cd $GITHUB_WORKSPACE
          cp -fv tests/default.behat.yml tests/behat.yml
          cp -fv tests/ci/config.php public_html/lists/config/config.php
          mkdir -p output/screenshots
          mkdir -p build/mails
          ./bin/start-selenium > output/selenium.log 2>&1 &
          sleep 5
          sudo php -S 0.0.0.0:80 -t public_html > /dev/null 2>&1 &

      - name: Check PHP syntax errors
        uses: overtrue/phplint@2.3.5
        with:
          path: ./public_html
          
      - name: Report Versions
        run: |
          google-chrome --version
          php -v
          chromedriver -v
          geckodriver -V
          which geckodriver
          which chromedriver
          firefox -v
          vendor/bin/behat -V

      - name: Run BDD Tests
        run: |
          cd $GITHUB_WORKSPACE/tests
          ../vendor/bin/behat -n -fprogress -p chrome --strict --stop-on-failure --tags=@initialise
          ../vendor/bin/behat -n -fprogress -p chrome --strict --stop-on-failure --tags="~@initialise && ~@wip"

      - name: Display output
        run: |
          cd $GITHUB_WORKSPACE
          cat output/selenium.log

      - name: Clean Up
        run: |
          cd $GITHUB_WORKSPACE
          cd ..
          mv phplist3 phplist-$RELEASE_VERSION
          find . -type d -exec chmod 755 {} \;
          find . -type f -exec chmod 644 {} \;
          cd phplist-$RELEASE_VERSION
          chmod 755 public_html/lists/admin/plugins
          rm -rf default.behat.yml TESTING.md .dotgitlab-ci.yml .travis.yml composer.json .php_cs .gitmodules .styleci.yml .gitignore .gitsvnextmodules tests public_html/lists/admin/tests scripts bin/start-selenium bin/fake-sendmail.sh bin/imgur-uploader.sh public_html/lists/base/tests public_html/lists/base/.htaccess public_html/lists/base/phpunit.xml.dist public_html/lists/base/composer.* public_html/lists/base/CODE_OF_CONDUCT.md public_html/lists/admin/ui/default
          cd ..
          zip -rq9 phplist-${RELEASE_VERSION}.zip phplist-${RELEASE_VERSION}
          tar zcf phplist-${RELEASE_VERSION}.tgz phplist-${RELEASE_VERSION}
          md5sum phplist-${RELEASE_VERSION}.* > phplist-${RELEASE_VERSION}.md5
          sha256sum phplist-${RELEASE_VERSION}.* > phplist-${RELEASE_VERSION}.sha256
          sha1sum phplist-${RELEASE_VERSION}.* > phplist-${RELEASE_VERSION}.sha1

      - name: Set up S3cmd cli tool
        uses: s3-actions/s3cmd@v1.1
        with:
          provider: aws
          region: 'us-east-1'
          access_key: ${{ secrets.AWS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Upload the files
        run: |
          s3cmd put phplist-${version}.* s3://${{ secrets.AWS_S3_BUCKET }}/versions/
          s3cmd put public_html/lists/admin/images/power-phplist.png s3://${{ secrets.AWS_S3_BUCKET }}/images/${version}/