# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    strategy:
      matrix:        
        php-versions: ['7.4']
        #php-versions: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

     # Runs a set of commands using the runners shell
      - name: Setup Packages
        run: |
          cd $GITHUB_WORKSPACE
          sudo apt update
          composer install

      - name: Create Database
        run: |
          sudo systemctl start mysql.service
          sudo mysql -proot  -e 'drop database if exists phplistdb'
          sudo mysqladmin -proot create phplistdb
          sudo mysql -proot -e 'grant all on phplistdb.* to phplist@"%" identified by "phplist"'

      - name: Set bootlist theme
        run: |
          cd $GITHUB_WORKSPACE/public_html/lists/admin/ui/
          wget https://github.com/phpList/phplist-ui-bootlist/archive/master.tar.gz
          tar -xzf master.tar.gz
          mv phplist-ui-bootlist-master phplist-ui-bootlist
          rm master.tar.gz

      - name: Start Test Server
        run: |
          cd $GITHUB_WORKSPACE
          cp -fv tests/ci/config.php public_html/lists/config/config.php
          ./bin/start-selenium > /dev/null 2>&1 &
          sleep 5
          sudo php -S 0.0.0.0:80 -t public_html > /dev/null 2>&1 &

      - name: Syntax Check
        run: |
          cd $GITHUB_WORKSPACE
          cd vendor/bin && ln -s ../njoannidi/php-lint-bash/phpLint 
          cd $GITHUB_WORKSPACE
          ./vendor/bin/phpLint ./public_html

      - name: Report Versions
        run: |
          google-chrome --version
          php -v
          chromedriver -v
          geckodriver -V
          firefox -v
          vendor/bin/behat -V

      - name: Run BDD Tests
        run: |
          cd $GITHUB_WORKSPACE/tests
          mkdir output
          mkdir -p build/mails
          ../vendor/bin/behat -n -fprogress -p firefox --strict --stop-on-failure --tags=@initialise
          ../vendor/bin/behat -n -fprogress -p chrome --strict --stop-on-failure --tags="~@initialise && ~@wip"
          ../vendor/bin/behat -n -fprogress -p firefox --strict --stop-on-failure --tags="~@initialise && ~@wip"
          ../vendor/bin/behat -n -fprogress -p goutte --strict --stop-on-failure --tags="~@initialise && ~@wip"


