# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run tests
        run: |
          cd $GITHUB_WORKSPACE
          sudo apt update
        #  sudo apt install -y composer php-mbstring php-curl php-mysql mariadb-client mariadb-server php-xml php-zip
          composer install
          sudo systemctl start mysql.service
          sudo mysql -e 'drop database if exists phplistdb'
          sudo mysqladmin create phplistdb
          sudo mysql -e 'grant all on phplistdb.* to phplist@"%" identified by "phplist"'
          cp -fv tests/ci/behat.yml behat.yml
          cp -fv tests/ci/config.php public_html/lists/config/config.php
          [[ ! -d public_html/lists/admin/ui/phplist-ui-bootlist ]] && { cd public_html/lists/admin/ui/ && wget https://github.com/phpList/phplist-ui-bootlist/archive/master.tar.gz && tar -xzf master.tar.gz && mv phplist-ui-bootlist-master phplist-ui-bootlist && rm master.tar.gz && cd ../../../../ }
          sudo php -S 0.0.0.0:80 -t public_html &
          cd tests 
          make test
